import type { Showroom } from "./types";

// Real network data ported from the production site (Changan-Website-ReDesign
// localisation/showrooms.jsx). The Casablanca/Rabat entries were collapsed into
// one buggy object upstream; restored here as two distinct showrooms.
export const showrooms: Showroom[] = [
  {
    slug: "casablanca",
    city: "Casablanca",
    address: "98 Boulevard Moulay Slimane, Casablanca 20253",
    phone: "+212 5 22 02 87 87",
    hours: "Lun–Jeu 8h30–18h30 · Ven 8h30–12h30 / 15h–18h30 · Sam 9h30–16h30",
    sav: "Lun–Jeu 8h30–18h30 · Ven 8h30–12h30 / 15h–18h30 · Sam 9h30–16h30",
    image: "/images/model/localisation/showroom-casablanca.webp",
    directionLink: "https://maps.google.com/?q=98+Boulevard+Moulay+Slimane,+Casablanca,+Maroc",
  },
  {
    slug: "rabat",
    city: "Rabat",
    address: "Gare Rabat Agdal, Rabat",
    phone: "+212 5 22 02 87 87",
    hours: "Lun–Jeu 8h30–18h30 · Ven 8h30–12h30 / 15h–18h30 · Sam 9h30–16h30",
    sav: "Lun–Jeu 8h30–18h30 · Ven 8h30–12h30 / 15h–18h30 · Sam 9h30–16h30",
    image: "/images/model/localisation/showroom-rabat.webp",
    directionLink: "https://maps.google.com/?q=Gare+Rabat+Agdal,+Rabat,+Maroc",
  },
  {
    slug: "tanger",
    city: "Tanger",
    address: "Riad Salam, Tranche 17, Route de Rabat, Tanger",
    phone: "+212 5 39 00 00 04",
    hours: "Lun–Sam 9h00–19h00",
    sav: "Lun–Ven 8h30–18h00",
    image: "/images/model/localisation/showroom-tanger.webp",
    directionLink: "https://maps.google.com/?q=Riad+Salam,+Route+de+Rabat,+Tanger,+Maroc",
  },
  {
    slug: "marrakech",
    city: "Marrakech",
    address: "N° 02, Rue Jordanie, Avenue Hassan II, Guéliz, Marrakech",
    phone: "+212 5 24 00 00 02",
    hours: "Lun–Sam 9h00–19h00",
    sav: "Lun–Ven 8h30–18h00",
    image: "/images/model/localisation/showroom-marrakech.webp",
    directionLink: "https://maps.google.com/?q=Rue+Jordanie,+Avenue+Hassan+II,+Gu%C3%A9liz,+Marrakech,+Maroc",
  },
  {
    slug: "kenitra",
    city: "Kénitra",
    address: "126A Av. Moulay Abdelaziz, Rue Kourd Ali, Kénitra",
    phone: "+212 5 30 00 00 01",
    hours: "Lun–Ven 8h30–18h30 · Sam 9h00–13h00",
    sav: "Lun–Ven 8h30–12h30 / 14h30–18h30",
    image: "/images/model/localisation/showroom-kenitra.webp",
    directionLink: "https://maps.google.com/?q=126A+Av.+Moulay+Abdelaziz,+K%C3%A9nitra,+Maroc",
  },
  {
    slug: "mohammedia",
    city: "Mohammedia",
    address: "Avenue Hassan II, BP 47, Mohammedia",
    phone: "+212 5 23 00 00 06",
    hours: "Lun–Sam 9h00–18h30",
    sav: "Lun–Ven 8h30–18h00",
    image: "/images/model/localisation/showroom-mohammedia.webp",
    directionLink: "https://maps.google.com/?q=Avenue+Hassan+II,+Mohammedia,+Maroc",
  },
  {
    slug: "el-jadida",
    city: "El Jadida",
    address: "Rte de Marrakech, Imm Abou El Faraj, Bd Bir Anzaran, El Jadida",
    phone: "+212 5 23 00 00 05",
    hours: "Lun–Ven 8h30–18h30 · Sam 9h00–13h00",
    sav: "Lun–Ven 8h30–12h30 / 14h30–18h30",
    image: "/images/model/localisation/showroom-eljadida.webp",
    directionLink: "https://maps.google.com/?q=Bd+Bir+Anzaran,+El+Jadida,+Maroc",
  },
  {
    slug: "tetouan",
    city: "Tétouan",
    address: "Avenue 9 Avril, Voie de contournement, B.P 211, Tétouan",
    phone: "+212 5 39 00 00 03",
    hours: "Lun–Sam 9h00–18h30",
    sav: "Lun–Ven 8h30–18h00",
    image: "/images/model/localisation/showroom-tetouan.webp",
    directionLink: "https://maps.google.com/?q=Avenue+9+Avril,+T%C3%A9touan,+Maroc",
  },
];
